[package]
name = "rust-psutil"
version = "0.1.0"
authors = ["andrei"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = "1.7.0"
clap = "2.33.0"